
require("FirebrowseR")
require("parallel")
require("plyr")




#' Download selected columns from the MAF generated by MutSig. Results may be filtered by gene, cohort, barcode and tool. At least one gene or barcode or cohort must be supplied.
#' @param tcga_participant_barcode A character vector containing TCGA barcodes, empty string queries all barcodes. See \code{\link{patient_barcodes}} for available barcodes. Remark that the data can NULL for barcode(s) which isn´t (aren´t) barcode(s) of the specified cohort.
#' @param cohort A character vector containing the cohort(s) to query, empty string queries all cohorts. See \code{\link{dn_cohorts}} for available cohorts.
#' @param gene A character vector containing gene symbols, empty string queries all genes. 
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use rather a small page.Size, e.g. page.Size = 250.
#' @param sort_by A character indicating the column which is used for sorting. The data can be sorted by tcga_participant_barcode, cohort, tool and gene.
#' @param tool Narrow search to include only data/results produced by the selected Firehose tool. Multiple values are allowed MutSig2.0, MutSig2CV. Default value is MutSig2CV.
#' @return data.frame of selected columns from the MAF generated by MutSig. 
#' @export
#' @seealso \code{dn_mutation.Exp} uses the service \code{\link{Analyses.Mutation.MAF}}, see \code{\link{FirebrowseR}}.
#' @examples
#' tcga_participant_barcode = "TCGA-AG-A002" # TCGA patient barcode from READ
#' cohort = "READ"
#' gene = c("A1BG", "A1CF", "A2M")
#' page.Size = 250
#' sort_by = "gene"
#' tool = "MutSig2CV"
#' obj = dn_mutation.Exp(tcga_participant_barcode, cohort, gene, page.Size, sort_by)
dn_mutation.Exp  = function(tcga_participant_barcode, cohort, gene, page.Size, sort_by, tool, filename=NULL){
  
  all.Found = F
  page.Counter = 1
  mut.Exp = list()

  while(all.Found == F){
   # tmp = Analyses.Mutation.MAF(format = "csv", cohort = cohort, tool = "MutSig2CV", gene = gene,
   #                             tcga_participant_barcode = tcga_participant_barcode, column = "", 
   #                             page = page.Counter,
   #                             page_size = page.Size, sort_by = sort_by)
    
    tmp = tryCatch( Analyses.Mutation.MAF(format = "csv", cohort = cohort, tool = "MutSig2CV", gene = gene,
                                         tcga_participant_barcode = tcga_participant_barcode, column = "", 
                                         page = page.Counter,
                                         page_size = page.Size, sort_by = sort_by), error=function(e) NULL)

    if(is.null(tmp)==TRUE || length(tmp)<1) {tmp = NULL; mut.Exp = as.data.frame(tmp); break;}
    
    mut.Exp[[page.Counter]] = tmp

    if(page.Counter > 1){
      colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
    }

    if(nrow(mut.Exp[[page.Counter]]) < page.Size){
      all.Found = T
    } else{
      page.Counter = page.Counter + 1
    }
  }

  if(is.null(mut.Exp)==TRUE ||length(mut.Exp)<1) {
    mut.Exp = NULL
    mut.Exp = as.data.frame(mut.Exp)
  } else{
    mut.Exp = rbind.fill(mut.Exp)
  }
  
  return(mut.Exp)

}




#' Download selected columns from the MAF generated by MutSig produced by the selected Firehose tool for one cohort.
#' @param cohort A character vector containing the cohort to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use rather a small page.Size, e.g. page.Size = 250.
#' @param tool Narrow search to include only data/results produced by the selected Firehose tool. Multiple values are allowed MutSig2.0,MutSig2CV. Default value is MutSig2CV.
#' @export
#' @seealso \code{dn_mutation_cohort} uses the service \code{\link{dn_mutation.Exp}}.
#' @examples
#' cohort = "READ"
#' page.Size = 1000
#' tool = "MutSig2CV"
#' read.mutation = dn_mutation_cohort(cohort, page.Size, tool)
dn_mutation_cohort = function(cohort, page.Size, tool, filename=NULL){

  cohort.mutation = list()
  cohort.clinical = dn_clinical_one(cohort)
  
  cohort.mutation = mclapply(cohort.clinical[,1], dn_mutation.Exp, cohort, "", page.Size, "gene", tool, mc.cores=detectCores()/10)
 # cohort.mutation = lapply(cohort.clinical[,1], dn_mutation.Exp, cohort, "", page.Size, "gene")

  if(is.null(cohort.mutation) || length(cohort.mutation)<1) {
    cohort.mutation = NULL
  } else{
    cohort.mutation = do.call(rbind.fill, cohort.mutation)
  }

  return(cohort.mutation)

}


