
require("FirebrowseR")
require("parallel")
require("plyr")




#' Download selected columns from the MAF generated by MutSig. Results may be filtered by gene, cohort, barcode and tool. At least one gene or barcode or cohort must be supplied.
#' @param tcga_participant_barcode A character vector containing TCGA barcodes, empty string queries all barcodes. See \code{\link{patient_barcodes}} for available barcodes. Remark that the data are NULL for barcode(s) which isn´t (aren´t) barcode(s) of the specified cohort.
#' @param cohort A character vector containing the cohort(s) to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param gene A character vector containing gene symbols. 
#' @param page.Size Number of records per page. For downloading data of single barcodes or genes the page.Size should be chosen small, i.e. 25, but usually not larger than 1000.
#' @param sort_by A character indicating the column which is used for sorting. The data can be sorted by tcga_participant_barcode, cohort, tool and gene.
#' @return data.frame of selected columns from the MAF generated by MutSig.
#' @export
#' @seealso \code{dn_mutation.Exp} uses the service \code{\link{Analyses.Mutation.MAF}}, see \code{\link{FirebrowseR}}.
#' @examples
#' tcga_participant_barcode = "TCGA-AG-A002" # a READ patient barcode
#' cohort = "READ"
#' gene = c("A1BG", "A1CF", "A2M")
#' page.Size = 250
#' sort_by = "gene"
#' obj = dn_mutation.Exp(tcga_participant_barcode, cohort, gene, page.Size, sort_by)
dn_mutation.Exp  = function(tcga_participant_barcode, cohort, gene, page.Size, sort_by, filename=NULL){

  all.Found = F
  page.Counter = 1
  mut.Exp = list()

  while(all.Found == F){
    tmp = Analyses.Mutation.MAF(format = "csv", cohort = cohort, tool = "MutSig2CV", gene = gene,
                                tcga_participant_barcode = tcga_participant_barcode, column = "", page = page.Counter,
                                page_size = page.Size, sort_by = sort_by)

    if( is.null(tmp)==TRUE) {tmp = NULL; break;}

    mut.Exp[[page.Counter]] = tmp

    if(page.Counter > 1){
      colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
    }

    if(nrow(mut.Exp[[page.Counter]]) < page.Size){
      all.Found = T
    } else{
      page.Counter = page.Counter + 1
    }
  }

  if(length(mut.Exp)<1) {
    mut.Exp = NULL
  } else{
    mut.Exp = rbind.fill(mut.Exp)
  }
  
  return(mut.Exp)

}




#' Download selected columns from the MAF generated by MutSig for one cohort.
#' @param cohort A character vector containing the cohort to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use a small page.Size, e.g. page.Size = 250.
#' @export
#' @seealso \code{dn_mutation_cohort} uses the service \code{\link{dn_mutation.Exp}}.
#' @examples
#' cohort = "READ"
#' page.Size = 2000
#' read.mutation = dn_mutation_cohort(cohort, page.Size)
dn_mutation_cohort = function(cohort, page.Size, filename=NULL){

  cohort.mutation = list()
  cohort.clinical = dn_clinical_one(cohort)
 # dn_mutation.Exp  = function(tcga_participant_barcode, cohort, gene, page.Size, sort_by, filename=NULL){
#   cohort.mutation = mclapply(cohort.clinical[,1], dn_mutation.Exp, cohort, "", page.Size, "gene", mc.cores=detectCores()/4)
cohort.mutation = lapply(cohort.clinical[,1], dn_mutation.Exp, cohort, "", page.Size, "gene")

  if(is.null(cohort.mutation) || length(cohort.mutation)<1) {
    cohort.mutation = NULL
  } else{
    cohort.mutation = do.call(rbind.fill, cohort.mutation)
  }

  return(cohort.mutation)

}


