require("FirebrowseR")
require("parallel")
require("plyr")



#' Download significantly mutated genes, as scored by MutSig. Results may be filtered by cohort, rank, gene, tool and/or Q-value threshold. At least one cohort or gene must be supplied.
#' @param cohort A character vector indicating the cohort(s) to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param rank Number of significant genes to return.
#' @param gene A character vector of gene symbols. See \code{\link{dn_gene_ID}} for available gene symbols.
#' @param page.Size Number of records per page.  Usually max is 2000.
#' @param sort_by A character indicating the column which is used for sorting. Data can be sorted by q, cohort, tool, gene and rank.
#' @return data.frame of selected columns from the MAF generated by MutSig.
#' @export
#' @seealso \code{dn_mutation_SMG.Exp} uses the service \code{\link{Analyses.Mutation.SMG}}, see \code{\link{FirebrowseR}}.

dn_mutation.SMG.Exp  = function(gene, rank, cohort, page.Size, sort_by, filename=NULL){

  all.Found = F
  page.Counter = 1
  mut.Exp = list()

  while(all.Found == F){
    tmp = Analyses.Mutation.SMG(format = "csv", cohort = cohort, tool = "MutSig2CV", rank = rank, gene = gene, q = "",
                                page = page.Counter, page_size = page.Size, sort_by = sort_by)

    if( is.null(tmp)==TRUE) {tmp = NULL; break;}

    mut.Exp[[page.Counter]] = tmp

    if(page.Counter > 1){
      colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
    }

    if(nrow(mut.Exp[[page.Counter]]) < page.Size){
      all.Found = T
    } else{
      page.Counter = page.Counter + 1
    }
  }

  if(length(mut.Exp)<1) {
    mut.Exp = NULL
  } else{
    mut.Exp = rbind.fill(mut.Exp)
  }

  return(mut.Exp)

}




#' Download selected columns from the MAF generated by MutSig for one cohort.
#' @param cohort A character vector indicating the cohort to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param gene_ID A character vector of all available gene symbols. See \code{\link{dn_gene_ID}} for downloading all gene symbols.
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use a small page.Size, e.g. page.Size = 250.
#' @return data.frame of selected columns from the MAF generated by MutSigof for all patient barcodes of the specified cohort.
#' @export
#' @seealso \code{dn_mutation_cohort} uses the service \code{\link{dn_mutation.Exp}}.

dn_mutation.SMG_cohort = function(cohort, gene_ID, page.Size, filename=NULL){

  mut.cohort = list()

  mut.cohort = mclapply(gene_ID[9:11], dn_mutation_SMG.Exp, "", cohort, page.Size, "gene", mc.cores=20) # mc.cores < 32

  if( is.null(mut.cohort) || length(mut.cohort)<1) {
    mut.cohort = NULL
  } else{
    mut.cohort = do.call(rbind.fill, mut.cohort)
  }

  return(mut.cohort)

}




#' @examples
#' tcga_participant_barcode = "TCGA-E9-A2JT" # it is a BRCA patient barcode
#' page.Size1 = 2000
#' gene_ID = dn_gene_ID(tcga_participant_barcode, page.Size1)
#' gene = c("A1BG", "A1CF", "A2M")
#' rank = ""
#' cohort = "ACC"
#' page.Size2 = 25
#' sort_by = "gene"
#' obj = dn_mutation.SMG.Exp(gene, rank, cohort, page.Size2, sort_by)
#' acc.mutation.SMG = dn_mutation.SMG_cohort(gene_ID, cohort, page.Size1)


