
require("FirebrowseR")
require("parallel")
require("plyr")



#' Download significantly mutated genes, as scored by MutSig. Results may be filtered by cohort, rank, gene, tool and/or Q-value threshold. At least one cohort or gene must be supplied.
#' @param cohort A character vector indicating the cohort(s) to query, empty string queries all cohorts. See \code{\link{dn_cohorts}} for available cohorts.
#' @param rank Number of significant genes to return.
#' @param gene A character vector of gene symbols, empty string queries all genes. 
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use a small page.Size, e.g. page.Size = 250.
#' @param sort_by A character indicating the column which is used for sorting. Data can be sorted by cohort, tool, gene and rank.
#' @return data.frame of selected columns from the MAF generated by MutSig.
#' @export
#' @seealso \code{dn_mutation_SMG.Exp} uses the service \code{\link{Analyses.Mutation.SMG}}, see \code{\link{FirebrowseR}}.
#' @examples
#' gene = c("A1BG", "A1CF", "A2M")
#' rank = ""
#' cohort = "ACC"
#' page.Size = 20
#' sort_by = "gene"
#' obj = dn_mutation.SMG.Exp(gene, rank, cohort, page.Size, sort_by)
dn_mutation.SMG.Exp  = function(gene, rank, cohort, page.Size, sort_by, filename=NULL){

  all.Found = F
  page.Counter = 1
  mut.Exp = list()

  while(all.Found == F){
    tmp = Analyses.Mutation.SMG(format = "csv", cohort = cohort, tool = "MutSig2CV", rank = rank, gene = gene, q = "",
                                page = page.Counter, page_size = page.Size, sort_by = sort_by)

    if( is.null(tmp)==TRUE || length(tmp)<1) { tmp = NULL; as.data.frame(tmp); break; }

    mut.Exp[[page.Counter]] = tmp

    if(page.Counter > 1){
      colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
    }

    if(nrow(mut.Exp[[page.Counter]]) < page.Size){
      all.Found = T
    } else{
      page.Counter = page.Counter + 1
    }
  }

  if(length(mut.Exp)<1) {
    mut.Exp = NULL
    as.data.frame(mut.Exp)
  } else{
    mut.Exp = rbind.fill(mut.Exp)
  }

  return(mut.Exp)

}




#' Download selected columns from the MAF generated by MutSig for one cohort.
#' @param cohort A character vector indicating the cohort to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param gene_ID A character vector of all available gene symbols. 
#' @param page.Size Number of records per page. Usually max is 2000. For cancers with small number of patients use a small page.Size, e.g. page.Size = 250.
#' @return data.frame of selected columns from the MAF generated by MutSigof for all patient barcodes of the specified cohort.
#' @export
#' @seealso \code{dn_mutation_cohort} uses the service \code{\link{dn_mutation.Exp}}.
#' @examples
#' cohort = "ACC"
#' page.Size = 1000
#' acc.mutation.SMG = dn_mutation.SMG_cohort(cohort, page.Size)
dn_mutation.SMG_cohort = function(cohort, gene_ID, page.Size, filename=NULL){

  mut.cohort = list()
                             
  mut.cohort = mclapply(gene_ID, dn_mutation_SMG.Exp, "", cohort, page.Size, "gene", mc.cores=detectCores()/2)

  if( is.null(mut.cohort) || length(mut.cohort)<1) {
    mut.cohort = NULL
  } else{
    mut.cohort = do.call(rbind.fill, mut.cohort)
  }

  return(mut.cohort)

}



