# source("dn_clinical.R")
require("FirebrowseR")
require("parallel")

# 1.
#' Download significantly mutated genes, as scored by MutSig. It may be filtered by cohort, rank, gene, tool and/or Q-value threshold. At least one cohort or gene must be supplied.
#' @param cohort A character vector indicating the cohort(s) to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param rank Number of significant genes to return.
#' @param gene A character vector of gene symbols. See \code{\link{dn_gene_ID}} for available gene symbols.
#' @param page.Size Number of records per page.
#' @param sort_by A character indicating the to column which is used for sorting. Data can be sorted by q, cohort, tool, gene and rank.
#' @return data.frame of selected columns from the MAF generated by MutSig.
#' @export
#' @seealso \code{dn_mutation_SMG.Exp} uses the service \code{\link{Analyses.Mutation.SMG}}, see \code{\link{FirebrowseR}}.
#----------------------------------------------alte Funktion:
dn_mutation_SMG.Exp  = function(gene, rank, cohort, page.Size, sort_by, filename=NULL){
# dn_mutation_SMG.Exp  = function(cohort, rank, gene, page.Size, sort_by, filename=NULL){

  all.Found = F
  page.Counter = 1
  mut.Exp = list()
  while(all.Found == F){
    tmp = Analyses.Mutation.SMG(format = "csv", cohort = cohort, tool = "MutSig2CV", rank = rank, gene = gene, q = "",
                                page = page.Counter, page_size = page.Size, sort_by = sort_by)

    if( is.null(tmp)==TRUE) {tmp = NULL; break;}
    # cat(tmp)
    mut.Exp[[page.Counter]] = tmp

    if(page.Counter > 1){
      colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
    }

    if(nrow(mut.Exp[[page.Counter]]) < page.Size){
      all.Found = T
    }
    else{
      page.Counter = page.Counter + 1
    }
  }

  if(length(mut.Exp)<1) {
    mut.Exp = NULL
  }
  else {
    mut.Exp = rbind.fill(mut.Exp)
  }
  cat(".")
  return(mut.Exp)

}

#-------------------------------
#dn_mutation.Exp = function(gene, cohort, tcga_participant_barcode, page.Size, sort_by, filename=NULL){
#dn_mutation.Exp = function(tcga_participant_barcode, cohort, gene, page.Size, sort_by, filename=NULL){
#  all.Found = F
#  page.Counter = 1
#  mut.Exp = list()
#  add.names = F

#  while(all.Found == F){
#     tmp = Analyses.Mutation.MAF(format = "csv", cohort = cohort, tool = "MutSig2CV", gene = gene,
#                               tcga_participant_barcode = tcga_participant_barcode, column = "", page = page.Counter,
#                                page_size = page.Size, sort_by = sort_by)

#     if( is.null(tmp)==TRUE) {tmp = NULL; break;}

# add barcode
#  if(page.Counter == 1 && !("tcga_participant_barcode" %in% colnames(tmp))) {
#     add.names = T
#  }
#  if(add.names) {
#     tmp = data.frame(tcga_participant_barcode=rep(tcga_participant_barcode, nrow(tmp)), tmp);
# }

#     mut.Exp[[page.Counter]] = tmp

#     if(page.Counter > 1){
#         colnames(mut.Exp[[page.Counter]]) = colnames(mut.Exp[[page.Counter-1]])
#     }

#     if(nrow(mut.Exp[[page.Counter]]) < page.Size){
#        all.Found = T
#     }
#    else{
#        page.Counter = page.Counter + 1
#     }
#  }

#  if(length(mut.Exp)<1) {
#    mut.Exp = NULL
#  }
#  else {
#    mut.Exp = do.call(rbind.fill,mut.Exp)
#  }
#  cat(".")
#  return(mut.Exp)

#}





#' Download selected columns from the MAF generated by MutSig for one cohort.
#' @param cohort A character vector indicating the cohort to query. See \code{\link{dn_cohorts}} for available cohorts.
#' @param page.Size Number of records per page.  For cancers with small number of patients use a small page.Size, e.g. page.Size = 25. If there is an error "Error in mut.cohort[[page.Counter]]: subscript out of bounds", try a smaller page.Size.
#' @return data.frame of selected columns from the MAF generated by MutSigof for all patient barcodes of the specified cohort.
#' @export
#' @seealso \code{dn_mutation_cohort} uses the service \code{\link{dn_mutation.Exp}}.

dn_mutation.SMG_cohort = function(cohort, page.Size, filename=NULL){

  mut.cohort = list()
  # dn_mutation_SMG.Exp  = function(cohort, rank, gene, page.Size, sort_by, filename=NULL){
  mut.cohort = mclapply(gene_ID, dn_mutation_SMG.Exp, cohort, "", page.Size, "gene", mc.cores=20) # mc.cores < 32
  #mut.cohort = lapply(cohort.clinical[,1], dn_mutation_SMG.Exp, cohort, "", page.Size, "tcga_participant_barcode")


  if( is.null(mut.cohort) || length(mut.cohort)<1) {
    mut.cohort = NULL
  }
  else{
    mut.cohort = do.call(rbind.fill, mut.cohort)
  }

  # for emergency
  #   bc = barcode(mut.cohort[,"Tumor_Sample_Barcode"])
  #   return(data.frame(tcga_patient_barcode=bc, mut.cohort))

  #return(mut.cohort)

  return (list(cohort=cohort.clinical[,1], data=mut.cohort))
}





#' @examples
#' tcga_participant_barcode = "TCGA-AG-A002" # it is a READ patient barcode
#' cohort = "READ"
#' gene = ""
#' page.Size1 = 25
#' sort_by = "gene"
#' obj = dn_mutation.Exp(tcga_participant_barcode, cohort, gene, page.Size, sort_by)
#' page.Size2 = 2000
#' mut.read = dn_mutation_cohort(cohort, page.Size)











